on:
  workflow_dispatch:
  push:
    branches: [main, master]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - name: Install ImageMagick (for webp conversion and Heatmap rasterisation)
        uses: mfinelli/setup-imagemagick@v6.0.0

      - name: Install system dependencies required for CRAN packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libglpk40 libMagick++-6

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true # required for pdf outputs


      - name: Install R version
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'

      - name: Install LOCAL Renv R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          # render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
